Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 11, in <module>
    from common.redis.helper_session import HelperSession
  File "/home/helperServer/weixin_helper/common/redis/helper_session.py", line 3, in <module>
    import redis, json
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 208, in <module>
    start_twisted_logging("hub_server")
  File "/home/helperServer/weixin_helper/common/utils/logger.py", line 39, in start_twisted_logging
    f = logfile.LogFile(file_path, "./", rotateLength=1024 * 1024, maxRotatedFiles=3)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 85, in _openFile
    self._file = open(self.path, "wb+", 0)
FileNotFoundError: [Errno 2] No such file or directory: './F:/tmp/wx_helper/hub_server/twisted_log.log'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 208, in <module>
    start_twisted_logging("hub_server")
  File "/home/helperServer/weixin_helper/common/utils/logger.py", line 39, in start_twisted_logging
    f = logfile.LogFile(file_path, "./", rotateLength=1024 * 1024, maxRotatedFiles=3)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 85, in _openFile
    self._file = open(self.path, "wb+", 0)
FileNotFoundError: [Errno 2] No such file or directory: './F:/tmp/wx_helper/hub_server/twisted_log.log'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 208, in <module>
    start_twisted_logging("hub_server")
  File "/home/helperServer/weixin_helper/common/utils/logger.py", line 39, in start_twisted_logging
    f = logfile.LogFile(file_path, "./", rotateLength=1024 * 1024, maxRotatedFiles=3)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 85, in _openFile
    self._file = open(self.path, "wb+", 0)
FileNotFoundError: [Errno 2] No such file or directory: './F:/tmp/wx_helper/hub_server/twisted_log.log'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 208, in <module>
    start_twisted_logging("hub_server")
  File "/home/helperServer/weixin_helper/common/utils/logger.py", line 39, in start_twisted_logging
    f = logfile.LogFile(file_path, "./", rotateLength=1024 * 1024, maxRotatedFiles=3)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 85, in _openFile
    self._file = open(self.path, "wb+", 0)
FileNotFoundError: [Errno 2] No such file or directory: './F:/tmp/wx_helper/hub_server/twisted_log.log'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 208, in <module>
    start_twisted_logging("hub_server")
  File "/home/helperServer/weixin_helper/common/utils/logger.py", line 39, in start_twisted_logging
    f = logfile.LogFile(file_path, "./", rotateLength=1024 * 1024, maxRotatedFiles=3)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 85, in _openFile
    self._file = open(self.path, "wb+", 0)
FileNotFoundError: [Errno 2] No such file or directory: './F:/tmp/wx_helper/hub_server/twisted_log.log'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 208, in <module>
    start_twisted_logging("hub_server")
  File "/home/helperServer/weixin_helper/common/utils/logger.py", line 39, in start_twisted_logging
    f = logfile.LogFile(file_path, "./", rotateLength=1024 * 1024, maxRotatedFiles=3)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 85, in _openFile
    self._file = open(self.path, "wb+", 0)
FileNotFoundError: [Errno 2] No such file or directory: './F:/tmp/wx_helper/hub_server/twisted_log.log'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 208, in <module>
    start_twisted_logging("hub_server")
  File "/home/helperServer/weixin_helper/common/utils/logger.py", line 39, in start_twisted_logging
    f = logfile.LogFile(file_path, "./", rotateLength=1024 * 1024, maxRotatedFiles=3)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 85, in _openFile
    self._file = open(self.path, "wb+", 0)
FileNotFoundError: [Errno 2] No such file or directory: './F:/tmp/wx_helper/hub_server/twisted_log.log'
Traceback (most recent call last):
  File "/home/helperServer/weixin_helper/hub/hub_server.py", line 208, in <module>
    start_twisted_logging("hub_server")
  File "/home/helperServer/weixin_helper/common/utils/logger.py", line 39, in start_twisted_logging
    f = logfile.LogFile(file_path, "./", rotateLength=1024 * 1024, maxRotatedFiles=3)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 170, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 45, in __init__
    self._openFile()
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 175, in _openFile
    BaseLogFile._openFile(self)
  File "/usr/local/Python3/lib/python3.6/site-packages/twisted/python/logfile.py", line 85, in _openFile
    self._file = open(self.path, "wb+", 0)
FileNotFoundError: [Errno 2] No such file or directory: './F:/tmp/wx_helper/hub_server/twisted_log.log'
